import AppKit
import Observation

struct Clip: Identifiable {
    let id = UUID()
    var text: String?
    var image: NSImage?
}

/// In-memory only: history is intentionally not persisted to disk.
@Observable final class ClipboardHistory {
    static let limit = 30
    /// nspasteboard.org markers that password managers set on secrets
    private static let ignoredTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    var clips: [Clip] = []

    @ObservationIgnored private var changeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var timer: Timer?

    init() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
    }

    func copy(_ clip: Clip) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        if let text = clip.text { pasteboard.setString(text, forType: .string) }
        if let image = clip.image { pasteboard.writeObjects([image]) }
        changeCount = pasteboard.changeCount
        clips.removeAll { $0.id == clip.id }
        clips.insert(clip, at: 0)
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.contains(where: Self.ignoredTypes.contains) else { return }

        if let text = pasteboard.string(forType: .string) {
            clips.removeAll { $0.text == text }
            clips.insert(Clip(text: text), at: 0)
        } else if let image = NSImage(pasteboard: pasteboard) {
            clips.insert(Clip(image: image), at: 0)
        }
        clips = Array(clips.prefix(Self.limit))
    }
}
